# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-08 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170806_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
