# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-13 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_video_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresourse',
            name='download',
            field=models.FileField(default='', max_length=200, upload_to='course/resource/%Y/%m', verbose_name='\u8bfe\u7a0b\u8d44\u6e90'),
        ),
    ]
