# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-14 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20170813_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=800, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
